// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMFrZ8nhSr6tLe5OlvhLoXmUpjFzDEbo',
    appId: '1:393527771745:web:12c79a43684ccd8a0aa020',
    messagingSenderId: '393527771745',
    projectId: 'cahtapp-e36e4',
    authDomain: 'cahtapp-e36e4.firebaseapp.com',
    storageBucket: 'cahtapp-e36e4.appspot.com',
    measurementId: 'G-DV17FF8G0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0rIHDhOqg-yPRiGoRVJTGSUljSgOCB2s',
    appId: '1:393527771745:android:d2993ba3d12c5de50aa020',
    messagingSenderId: '393527771745',
    projectId: 'cahtapp-e36e4',
    storageBucket: 'cahtapp-e36e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD75o8t8Zu66SCYxYgzbP5uIKToROjVDUM',
    appId: '1:393527771745:ios:f7278af47c2354c00aa020',
    messagingSenderId: '393527771745',
    projectId: 'cahtapp-e36e4',
    storageBucket: 'cahtapp-e36e4.appspot.com',
    iosBundleId: 'com.example.cahtapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD75o8t8Zu66SCYxYgzbP5uIKToROjVDUM',
    appId: '1:393527771745:ios:f7278af47c2354c00aa020',
    messagingSenderId: '393527771745',
    projectId: 'cahtapp-e36e4',
    storageBucket: 'cahtapp-e36e4.appspot.com',
    iosBundleId: 'com.example.cahtapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLMFrZ8nhSr6tLe5OlvhLoXmUpjFzDEbo',
    appId: '1:393527771745:web:12b1607b1c68f5320aa020',
    messagingSenderId: '393527771745',
    projectId: 'cahtapp-e36e4',
    authDomain: 'cahtapp-e36e4.firebaseapp.com',
    storageBucket: 'cahtapp-e36e4.appspot.com',
    measurementId: 'G-5RPGRV3MZL',
  );
}
